<?php

use Krystal\Form\Element;
use Krystal\Form\HtmlHelper;
use Krystal\Grid\Grid;

defined('KRYSTAL') or die;

?>

<form action="<?= $route; ?>">
    <div class="row">
        <div class="col-lg-1">
            <div class="btn-toolbar">
                <div class="btn-group">
                  <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
                    <i class="glyphicon glyphicon-list"></i> <?php $this->show('Menu'); ?> <span class="caret"></span>
                  </button>

                  <ul class="dropdown-menu">
                     <li><a href="<?php echo $this->url('News:Admin:Post@addAction'); ?>"><i class="glyphicon glyphicon-file"></i> <?php $this->show('Add new post'); ?></a></li>
                     <li><a href="<?php echo $this->url('News:Admin:Category@addAction'); ?>"><i class="glyphicon glyphicon-folder-open"></i> <?php $this->show('Add new category'); ?></a></li>
                     <li><a href="<?php echo $this->url('News:Admin:Config@indexAction'); ?>"><i class="glyphicon glyphicon-tasks"></i> <?php $this->show('Configuration'); ?></a></li>
                     <li class="divider"></li>
                     <li class="dropdown-header"><?php $this->show('Actions'); ?></li>
                     
                     <?php if (!empty($posts)): ?>
                     <li><a href="#" data-button="save-changes" data-url="<?php echo $this->url('News:Admin:Post@tweakAction'); ?>"><i class="glyphicon glyphicon-floppy-save"></i> <?php $this->show('Save changes'); ?></a></li>
                     <li><a href="#" data-button="remove-selected" data-url="<?php echo $this->url('News:Admin:Post@deleteAction', null); ?>"><i class="glyphicon glyphicon-remove"></i> <?php $this->show('Remove selected'); ?></a></li>
                     
                     <?php else: ?>
                     <li class="disabled"><a><i class="glyphicon glyphicon-floppy-save"></i> <?php $this->show('Save changes'); ?></a></li>
                     <li class="disabled"><a><i class="glyphicon glyphicon-remove"></i> <?php $this->show('Remove selected'); ?></a></li>
                     <?php endif; ?>
                  </ul>
                </div>
            </div>
        </div>

        <div class="col-lg-3">
            <button type="submit" class="btn btn-primary"><i class="glyphicon glyphicon-search" aria-hidden="true"></i> <? $this->show('Filter'); ?></button>
        </div>
    </div>
    
    <div class="row">
        <div class="col-lg-8">
                <?php $this->loadPartial('items-per-page', array('caption' => 'News')); ?>

                <?= Grid::render($posts, array(
                    // A column to be considered as a primary key
                    'pk' => 'id',
                    'batch' => true,
                    'tableClass' => 'table table-hover table-bordered table-striped table-condensed',
                    'columns' => array(
                        array(
                            'column' => 'id',
                            'label' => '#'
                        ),

                        array(
                            'column' => 'name',
                            'type' => 'text',
                            'filter' => true
                        ),

                        array(
                            'column' => 'date',
                            'type' => 'text',
                            'filter' => false,
                            'value' => function($entity){
                                return $entity->getTimeBag()->getPanelFormat();
                            }
                        ),

                        array(
                            'column' => 'category_name',
                            'name' => 'category_id', // Set explicit name
                            'label' => 'Category',
                            'type' => 'select',
                            'filter' => $categoryList
                        ),

                        array(
                            'column' => 'published',
                            'type' => 'select',
                            'filter' => true,
                            'value' => function($row){
                                return Element::checkbox(sprintf('published[%s]', $row['id']), $row['published']);
                            },
                            'filter' => $this->translateArray([
                                '0' => 'No',
                                '1' => 'Yes',
                            ])
                        ),

                        array(
                            'column' => 'seo',
                            'label' => 'SEO',
                            'filter' => true,
                            'type' => 'select',
                            'value' => function($row){
                                return Element::checkbox(sprintf('seo[%s]', $row['id']), $row['seo']);
                            },
                            'filter' => $this->translateArray([
                                '0' => 'No',
                                '1' => 'Yes'
                            ])
                        ),

                        array(
                            'column' => 'front',
                            'type' => 'select',
                            'value' => function($row){
                                return Element::checkbox(sprintf('front[%s]', $row['id']), $row['front']);
                            },
                            'filter' => $this->translateArray([
                                '0' => 'No',
                                '1' => 'Yes'
                            ])
                        )
                    ),

                    'actions' => array(
                        'polls' => function($row) use ($loadedModules){
                            // If polls module is loaded, then show its link
                            if (in_array('Polls', $loadedModules)) {
                                // Create dynamic URL
                                $url = $this->createQueryUrl('Polls:Admin:WebPage@indexAction', array(
                                    'web_page_id' => $row['webpageid'], 
                                    'title' => rawurlencode($row['name']),
                                    'module' => 'News',
                                    'back_url' => rawurlencode($this->url('News:Admin:Browser@indexAction', null))
                                ));

                                return Element::icon('glyphicon glyphicon-star', $url, array('data-toggle' => 'tooltip', 'data-placement' => 'left', 'data-original-title' => $this->translate('Polls of this page')));
                                
                            } else {
                                // Polls module is not loaded, so just skip creating this link
                                return null;
                            }
                        },

                        'view' => function($row){
                            return Element::icon('glyphicon glyphicon-search', $row['url'], array('data-toggle' => 'tooltip', 'data-placement' => 'left', 'data-original-title' => $this->translate('View this post'), 'data-button' => 'view', 'target' => '_blank'));
                        },

                        'edit' => function($row){
                            return Element::icon('glyphicon glyphicon-pencil', $this->url('News:Admin:Post@editAction', $row['id']), array('data-toggle' => 'tooltip', 'data-placement' => 'left', 'data-original-title' => $this->translate('Edit this post'), 'data-button' => 'edit'));
                        },

                        'remove' => function($row){
                            return Element::icon('glyphicon glyphicon-remove', '#', array('data-toggle' => 'tooltip', 'data-placement' => 'left', 'data-original-title' => $this->translate('Remove this post'), 'data-button' => 'delete', 'data-url' => $this->url('News:Admin:Post@deleteAction', $row['id'])));
                        }
                    )

                ), $this->translator, $route, $query); ?>

                <?php if (empty($posts)): ?>
                <div class="center-block">
                    <h2 class="text-center text-muted"><i class="glyphicon glyphicon-remove"></i> <?php $this->show('No news'); ?></h2>
                </div>
                <?php endif; ?>

                <?php $this->loadPartial('paginator'); ?>
        </div>

        <div class="col-lg-4">
            <div class="table-responsive">
                <h4><i class="glyphicon glyphicon-th-list"></i> <?php $this->show('Categories'); ?> (<?php echo count($categories); ?>)</h4>

                <div class="table-responsive">
                    <table class="table table-hover table-bordered table-striped table-condensed">
                        <thead>
                            <tr>
                                <th class="text-center"><?php $this->show('#'); ?></th>
                                <th class="text-center"><?php $this->show('Name'); ?></th>
                                <th class="text-center"><?php $this->show('Amount of news'); ?></th>
                                <th class="text-center"><?php $this->show('Actions'); ?></th>
                            </tr>
                        </thead>
                        
                        <?php if (!empty($categories)): ?>
                        <tbody>
                            <?php foreach ($categories as $category): ?>
                            <tr class="<?php echo HtmlHelper::addOnDemand(isset($categoryId) && $categoryId == $category->getId(), 'info'); ?>">
                                <td class="text-center text-muted"><?php echo $category->getId(); ?></td>
                                <td>
                                    <a href="<?php echo $this->url('News:Admin:Browser@categoryAction', $category->getId()); ?>"><?php echo $category->getName(); ?></a>
                                </td>
                                <td class="text-center"><?php echo $category->getPostCount(); ?></td>
                                <td class="text-center">
                                    <a data-button="view" data-toggle="tooltip" data-placement="left" data-original-title="<?php $this->show('View this category on site'); ?>" target="_blank" href="<?php echo $category->getUrl();?>"><i class="glyphicon glyphicon-search"></i></a>
                                    <a data-toggle="tooltip" data-placement="left" data-original-title="<?php $this->show('Edit this category'); ?>" data-button="edit" href="<?php echo $this->url('News:Admin:Category@editAction', $category->getId()); ?>"><i class="glyphicon glyphicon-pencil"></i></a>
                                    <a data-toggle="tooltip" data-placement="left" data-original-title="<?php $this->show('Remove this category'); ?>" data-button="delete" data-url="<?php echo $this->url('News:Admin:Category@deleteAction', $category->getId()); ?>" href="#"><i class="glyphicon glyphicon-remove"></i></a>
                                </td>
                            </tr>
                            <?php endforeach; ?>
                        </tbody>
                        <?php endif; ?>
                        
                    </table>
                    
                    <?php if (empty($categories)): ?>
                    <div class="center-block">
                        <h2 class="text-center text-muted"><i class="glyphicon glyphicon-remove"></i> <?php $this->show('No categories'); ?></h2>
                    </div>
                    <?php endif; ?>
                    
                </div>
            </div>
        </div>
    </div>


</form>
