<?php

use Krystal\Form\Element;
defined('KRYSTAL') or die;

?>

<form data-group="image">
    <div class="well">
        <?php echo Element::hidden('image[id]', $image->getId()); ?>
        <?php echo Element::hidden('image[image]', $image->getImage()); ?>
        <?php echo Element::hidden('image[post_id]', $image->getPostId()); ?>

        <div class="form-group">
            <label class="col-lg-2 control-label"><?php $this->show('Image'); ?></label>
            <div class="col-lg-10">
                <p>
                    <img data-image="<?php echo $image->getId() ? null : 'preview'; ?>" src="<?php echo $image->getImageUrl('400x400'); ?>" />
                </p>

                <a class="btn btn-primary" data-button="upload" data-target="[name='file']" href="#"><i class="glyphicon glyphicon-picture"></i> <?php $this->show('Upload a file'); ?></a>
                <?php echo Element::file('file', 'image/x-png, image/gif, image/jpeg', array('class' => 'hidden', 'data-plugin' => 'preview')); ?>
            </div>
        </div>

		<div class="form-group">
			<label class="col-lg-2 control-label"><?php $this->show('Order'); ?></label>
			<div class="col-lg-10">
				<div class="input-group">
                    <?php echo Element::text('image[order]', $image->getOrder(), array('class' => 'form-control', 'placeholder' => $this->translate('Sorting order'))); ?>
					<span class="input-group-addon"><i class="glyphicon glyphicon-pencil"></i></span>
				</div>
			</div>
		</div>
	</div>

    <?php $this->loadPartial('actions', array(
        'new' => !$image->getId(),
        'add' => array('News:Admin:PostGallery@addAction', $image->getPostId()),
        'edit' => 'News:Admin:PostGallery@editAction',
        'save' => 'News:Admin:PostGallery@saveAction',
        'cancel' => array('News:Admin:Post@editAction', $image->getPostId())
    )); ?>

</form>
