<?php

use Krystal\Grid\Grid;
use Krystal\Form\Element;
use Krystal\Security\Filter;
use Cms\Service\LanguageManager;
use Cms\View\Icon;

defined('KRYSTAL') or die;

?>

<?php if (!empty($categories)): ?>

<form data-group="post" autocomplete="off">
    <ul class="nav nav-tabs" role="tablist">
        <li role="presentation" class="active"><a href="#data" role="tab" data-toggle="tab"><i class="glyphicon glyphicon-file"></i> <?php $this->show('Data'); ?></a></li>
        <li role="presentation"><a href="#configuration" role="tab" data-toggle="tab"><i class="glyphicon glyphicon-th-list"></i> <?php $this->show('Configuration'); ?></a></li>
        <?php if (!is_object($post)): ?>
        <li role="presentation"><a href="#gallery" role="tab" data-toggle="tab"><i class="glyphicon glyphicon-picture"></i> <?php $this->show('Gallery'); ?></a></li>
        <?php endif; ?>
    </ul>

    <div class="tab-content">
        <div role="tabpanel" class="tab-pane active" id="data">
            <div class="well">
                <?php $this->loadPartial('language-tabs'); ?>

                <div class="tab-content">
                    <?php foreach ($languages as $index => $language): ?>
                    <div class="tab-pane fade in <?php echo $index == 0 ? 'active' : null; ?>" id="<?php printf('language-%s', $language->getId()); ?>" role="tabpanel">
                        <?php $entity = LanguageManager::findByLangId($language->getId(), $post); ?>

                        <?php echo Element::hidden(sprintf('translation[%s][id]', $language->getId()), $entity->getId()); ?>
                        <?php echo Element::hidden(sprintf('translation[%s][web_page_id]', $language->getId()), $entity->getWebPageId()); ?>
                        <?php echo Element::hidden(sprintf('translation[%s][lang_id]', $language->getId()), $language->getId()); ?>

                        <?php $this->loadPartial('language-name', array('language' => $language)); ?>

                        <div class="form-group">
                            <label class="col-lg-2 control-label"><?php $this->show('Name'); ?></label>
                            <div class="col-lg-10">
                                <div class="input-group">
                                    <?php echo Element::text(sprintf('translation[%s][name]', $language->getId()), Filter::charsDecode($entity->getName()), array('class' => 'form-control', 'placeholder' => $this->translate('Post name'))); ?>
                                    <span class="input-group-addon"><i class="glyphicon glyphicon-pencil"></i></span>
                                </div>
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-lg-2 control-label"><?php $this->show('Introduction'); ?></label>
                            <div class="col-lg-10">
                                <?php echo Element::textarea(sprintf('translation[%s][intro]', $language->getId()), $entity->getIntro(), array('data-wysiwyg' => 'true')); ?>
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-lg-2 control-label"><?php $this->show('Full text'); ?></label>
                            <div class="col-lg-10">
                                <?php echo Element::textarea(sprintf('translation[%s][full]', $language->getId()), $entity->getFull(), array('data-wysiwyg' => 'true')); ?>
                            </div>
                        </div>

                        <div class="options">
                            <div class="form-group">
                                <label class="col-lg-2 control-label"><?php $this->show('Slug'); ?></label>
                                <div class="col-lg-10">
                                    <div class="input-group">
                                        <?php echo Element::text(sprintf('translation[%s][slug]', $language->getId()), $entity->getSlug(), array('class' => 'form-control', 'data-input' => 'slug', 'placeholder' => $this->translate('URL slug for this post. By default is taken from the name'))); ?>
                                        <span class="input-group-addon">
                                            <a href="#" data-button="slug"><i class="glyphicon glyphicon-refresh" data-toggle="tooltip" title="<?php $this->show('Refresh the slug'); ?>"></i></a>
                                        </span>
                                    </div>
                                </div>
                            </div>

                            <div class="form-group">
                                <label class="col-lg-2 control-label"><?php $this->show('Title'); ?></label>
                                <div class="col-lg-10">
                                    <div class="input-group">
                                        <?php echo Element::text(sprintf('translation[%s][title]', $language->getId()), Filter::charsDecode($entity->getTitle()), array('class' => 'form-control', 'data-input' => 'title', 'placeholder' => $this->translate("Post's title"))); ?>
                                        <span class="input-group-addon"><i class="glyphicon glyphicon-pencil"></i></span>
                                    </div>
                                </div>
                            </div>

                            <div class="form-group">
                                <label class="col-lg-2 control-label"><?php $this->show('Keywords'); ?></label>
                                <div class="col-lg-10">
                                    <?php echo Element::textarea(sprintf('translation[%s][keywords]', $language->getId()), $entity->getKeywords(), array('class' => 'form-control', 'placeholder' => $this->translate('Keywords used for search engines'))); ?>
                                </div>
                            </div>

                            <div class="form-group">
                                <label class="col-lg-2 control-label"><?php $this->show('Description'); ?></label>
                                <div class="col-lg-10">
                                    <?php echo Element::textarea(sprintf('translation[%s][meta_description]', $language->getId()), $entity->getMetaDescription(), array('class' => 'form-control', 'placeholder' => $this->translate('Meta description for search engines'))); ?>
                                </div>
                            </div>
                        </div>
                    </div>
                    <?php endforeach; ?>
                </div>
            </div>
            
            <?php $this->loadPartial('actions', array(
                'new' => !$entity->getId(),
                'add' => 'News:Admin:Post@addAction',
                'edit' => 'News:Admin:Post@editAction',
                'save' => 'News:Admin:Post@saveAction',
                'cancel' => 'News:Admin:Browser@indexAction',
                'options' => true
            )); ?>

        </div>

        <div role="tabpanel" class="tab-pane" id="configuration">
            <div class="well">
                <?php echo Element::hidden('post[id]', $entity->getId()); ?>
                <?php echo Element::hidden('post[cover]', $entity->getCover()); ?>

                <?php if (isset($posts)): ?>
                <div class="form-group">
                    <label class="col-lg-2 control-label"><?php $this->show('Attached posts'); ?></label>
                    <div class="col-lg-10">
                        <?php echo Element::select('post[attached][]', $posts, $entity->getAttachedIds(), array('class' => 'form-control', 'data-plugin' => 'chosen', 'data-placeholder' => ' ', 'multiple' => true)); ?>
                    </div>
                </div>
                <?php endif; ?>

                <div class="form-group">
                    <label class="col-lg-2 control-label"><?php $this->show('Front'); ?></label>
                    <div class="col-lg-10">
                        <?php echo Element::checkbox('post[front]', $entity->getFront(), array('class' => 'form-control')); ?>
                    </div>
                </div>

                <div class="form-group">
                    <label class="col-lg-2 control-label"><?php $this->show('Published'); ?></label>
                    <div class="col-lg-10">
                        <?php echo Element::checkbox('post[published]', $entity->getPublished(), array('class' => 'form-control')); ?>
                    </div>
                </div>

                <div class="form-group">
                    <label class="col-lg-2 control-label"><?php $this->show('Enable SEO'); ?></label>
                    <div class="col-lg-10">
                        <?php echo Element::checkbox('post[seo]', $entity->getSeo(), array('class' => 'form-control')); ?>
                    </div>
                </div>

                <div class="form-group">
                    <label class="col-lg-2 control-label"><?php $this->show('Category'); ?></label>
                    <div class="col-lg-10">
                        <?php echo Element::select('post[category_id]', $categories, $entity->getCategoryId(), array('class' => 'form-control')); ?>
                    </div>
                </div>

                <div class="form-group">
                    <label class="col-lg-2 control-label"><?php $this->show('Date'); ?></label>
                    <div class="col-lg-10">
                        <div class="input-group date">
                            <?php echo Element::text('post[date]', $entity->getTimeBag()->getPanelFormat(), array('class' => 'form-control', 'placeholder' => $this->translate('Date of the post'))); ?>
                            <span class="input-group-addon"><i class="glyphicon glyphicon-calendar" data-toggle="tooltip" title="<?php $this->show('Change the date'); ?>"></i></span>
                        </div>
                    </div>
                </div>

                <!--Cover-->
                <div class="form-group">
                    <label class="col-lg-2 control-label"><?php $this->show('Cover'); ?></label>
                    <div class="col-lg-10">
                        <?php if ($entity->hasCover()): ?>
                        <p><img data-image="preview" src="<?php echo $entity->getImageUrl('200x200'); ?>" /></p>
                        <p>
                            <label for="removeCover"><?php $this->show('Remove this cover'); ?>&nbsp;</label>
                            <input type="checkbox" id="removeCover" name="post[remove_cover]" data-toggle="tooltip" data-placement="left" title="<?php $this->show('Check it if you want to remove this cover'); ?>" />
                        </p>

                        <?php else: ?>
                        <p><img data-image="preview" /></p>
                        <?php endif; ?>

                        <a class="btn btn-primary" data-button="upload" data-target="[name='file']" href="#"><i class="glyphicon glyphicon-picture"></i> <?php $this->show('Upload a file'); ?></a>
                        <?php echo Element::file('file', 'image/x-png, image/gif, image/jpeg', array('class' => 'hidden', 'data-plugin' => 'preview')); ?>
                    </div>
                </div>
                <!--/Cover-->
            </div>
        </div>

        <?php if (!is_object($post)): ?>
        <div role="tabpanel" class="tab-pane" id="gallery">
            <h2 class="page-header"><i class="glyphicon glyphicon-picture"></i> <?php $this->show('Gallery'); ?> <small>(<?= count($images); ?>)</small></h2>

            <p>
                <a class="btn btn-primary" href="<?php echo $this->url('News:Admin:PostGallery@addAction', $entity->getId()); ?>"><i class="glyphicon glyphicon-picture"></i> <?php $this->show('Add new image'); ?></a>
            </p>

            <?= Grid::render($images, array(
                'tableClass' => 'table table-hover table-bordered table-striped table-condensed',
                'columns' => array(
                    array(
                        'column' => 'image',
                        'value' => function($entity){
                            return Element::image($entity->getImageUrl('400x400'), array('class' => 'img-responsive center-block'));
                        }
                    ),
                    array(
                        'column' => 'order'
                    )
                ),

                'actions' => array(
                    'edit' => function($entity){
                        return Icon::edit(
                            $this->url('News:Admin:PostGallery@editAction', $entity['id']),
                            $this->translate('Edit this image')
                        );
                    },

                    'delete' => function($entity){
                        return Icon::remove(
                            $this->url('News:Admin:PostGallery@deleteAction', $entity['id']),
                            $this->translate('Remove this image')
                        );
                    }
                )

            ), $this->translator); ?>

        </div>
        <?php endif; ?>
    </div>
</form>

<?php else: ?>

<div class="well">
 <div class="center-block">
  <h2 class="text-muted text-center"><i class="glyphicon glyphicon-remove"></i> <?php $this->show('Before you add a post, you need to create at least one category'); ?></h2>
 </div>
</div>

<?php endif; ?>
