<?php

use Krystal\Form\Element;

?>

<?php if (!empty($categories)): ?>

<form data-group="post">
    <div class="well clearfix">
        
        <?php echo Element::hidden('post[id]', $post->getId()); ?>
        <?php echo Element::hidden('post[web_page_id]', $post->getWebPageId()); ?>
        <?php echo Element::hidden('post[cover]', $post->getCover()); ?>
        
        <div class="form-group clearfix">
            <label class="col-lg-2 control-label"><?php $this->show('Name'); ?></label>
            <div class="col-lg-10">
                <div class="input-group">
                    <?php echo Element::text('post[name]', $post->getName(), array('class' => 'form-control', 'placeholder' => $this->translate("Post's name"))); ?>
                    <span class="input-group-addon"><i class="glyphicon glyphicon-pencil"></i></span>
                </div>
            </div>
        </div>
        
        <div class="form-group clearfix">
            <label class="col-lg-2 control-label"><?php $this->show('Category'); ?></label>
            <div class="col-lg-10">
                <?php echo Element::select('post[category_id]', $categories, $post->getCategoryId(), array('class' => 'form-control')); ?>
            </div>
        </div>
        
        <div class="form-group clearfix">
            <label class="col-lg-2 control-label"><?php $this->show('Introduction'); ?></label>
            <div class="col-lg-10">
                <?php echo Element::textarea('post[intro]', $post->getIntro(), array('data-wysiwyg' => 'true')); ?>
            </div>
        </div>
        
        <div class="form-group clearfix">
            <label class="col-lg-2 control-label"><?php $this->show('Full text'); ?></label>
            <div class="col-lg-10">
                <?php echo Element::textarea('post[full]', $post->getFull(), array('data-wysiwyg' => 'true')); ?>
            </div>
        </div>
        
        <div class="options">
            
            <div class="form-group clearfix">
                <label class="col-lg-2 control-label"><?php $this->show('Date'); ?></label>
                <div class="col-lg-10">
                    <div class="input-group date">
                        <?php echo Element::text('post[date]', $post->getTimeBag()->getPanelFormat(), array('class' => 'form-control', 'placeholder' => $this->translate('Date of the post'))); ?>
                        <span class="input-group-addon"><i class="glyphicon glyphicon-calendar" data-toggle="tooltip" title="<?php $this->show('Change the date'); ?>"></i></span>
                    </div>
                </div>
            </div>
            
            <div class="form-group clearfix">
                <label class="col-lg-2 control-label"><?php $this->show('Published'); ?></label>
                <div class="col-lg-10">
                    <?php echo Element::checkbox('post[published]', $post->getPublished(), array('class' => 'form-control')); ?>
                </div>
            </div>
            
            <div class="form-group clearfix">
                <label class="col-lg-2 control-label"><?php $this->show('Enable SEO'); ?></label>
                <div class="col-lg-10">
                    <?php echo Element::checkbox('post[seo]', $post->getSeo(), array('class' => 'form-control')); ?>
                </div>
            </div>
            
            <div class="form-group clearfix">
                <label class="col-lg-2 control-label"><?php $this->show('Slug'); ?></label>
                <div class="col-lg-10">
                    <div class="input-group">
                        <?php echo Element::text('post[slug]', $post->getSlug(), array('class' => 'form-control', 'data-input' => 'slug', 'placeholder' => $this->translate('URL slug for this post. By default is taken from the name'))); ?>
                        <span class="input-group-addon">
                            <a href="#" data-button="slug"><i class="glyphicon glyphicon-refresh" data-toggle="tooltip" title="<?php $this->show('Refresh the slug'); ?>"></i></a>
                        </span>
                    </div>
                </div>
            </div>
            
            <div class="form-group clearfix">
                <label class="col-lg-2 control-label"><?php $this->show('Title'); ?></label>
                <div class="col-lg-10">
                    <div class="input-group">
                        <?php echo Element::text('post[title]', $post->getTitle(), array('class' => 'form-control', 'data-input' => 'title', 'placeholder' => $this->translate("Post's title"))); ?>
                        <span class="input-group-addon"><i class="glyphicon glyphicon-pencil"></i></span>
                    </div>
                </div>
            </div>
            
            <div class="form-group clearfix">
                <label class="col-lg-2 control-label"><?php $this->show('Keywords'); ?></label>
                <div class="col-lg-10">
                    <div class="input-group">
                        <?php echo Element::text('post[keywords]', $post->getKeywords(), array('class' => 'form-control', 'placeholder' => $this->translate('Keywords used for search engines'))); ?>
                        <span class="input-group-addon"><i class="glyphicon glyphicon-tags"></i></span>
                    </div>
                </div>
            </div>
            
            <div class="form-group clearfix">
                <label class="col-lg-2 control-label"><?php $this->show('Description'); ?></label>
                <div class="col-lg-10">
                    <?php echo Element::textarea('post[meta_description]', $post->getMetaDescription(), array('class' => 'form-control', 'placeholder' => $this->translate('Meta description for search engines'))); ?>
                </div>
            </div>
            
            <!--Cover-->
            <div class="form-group clearfix">
                <label class="col-lg-2 control-label"><?php $this->show('Cover'); ?></label>
                <div class="col-lg-10">
                    <br />
                    
                    <?php if ($post->hasCover()): ?>
                    <img data-image="preview" src="<?php echo $post->getImageBag()->getUrl('200x200'); ?>" data-zoom-image="<?php echo $post->getImageBag()->getUrl('original'); ?>" />
                    
                    <br />
                    <br />
                    
                    <div>
                        <label for="removeCover"><?php $this->show('Remove this cover'); ?>&nbsp;</label>
                        <input type="checkbox" id="removeCover" name="post[remove_cover]" data-toggle="tooltip" data-placement="left" title="<?php $this->show('Check it if you want to remove this cover'); ?>" />
                    </div>
                    
                    <br />
                    
                    <?php else: ?>
                    <img data-image="preview" />
                    <?php endif; ?>
                    
                    <br />
                    <br />
                    
                    <?php echo Element::file('file', 'image/x-png, image/gif, image/jpeg'); ?>
                </div>
            </div>
            <!--/Cover-->
            
        </div>
    </div>
    
    <?php if ($post->getId()): ?>
    
    <button data-button="save" data-url="<?php echo $this->url('News:Admin:Post@saveAction'); ?>" class="btn btn-primary"><i class="glyphicon glyphicon-floppy-save"></i> <?php $this->show('Save'); ?></button>
    <button data-button="save-create" data-back-url="<?php echo $this->url('News:Admin:Post@addAction'); ?>" data-url="<?php echo $this->url('News:Admin:Post@saveAction'); ?>" class="btn btn-primary"><i class="glyphicon glyphicon-floppy-open"></i> <?php $this->show('Save & Create new'); ?></button>
    
    <?php else: ?>
    
    <button data-button="add" data-back-url="<?php echo $this->url('News:Admin:Post@editAction', null); ?>" data-url="<?php echo $this->url('News:Admin:Post@saveAction'); ?>" class="btn btn-primary"><i class="glyphicon glyphicon-floppy-save"></i> <?php $this->show('Add'); ?></button>
    <button data-button="add-create" data-url="<?php echo $this->url('News:Admin:Post@saveAction'); ?>" class="btn btn-primary"><i class="glyphicon glyphicon-floppy-open"></i> <?php $this->show('Add & Create new'); ?></button>
    
    <?php endif; ?>
    
    <button data-button="options" class="btn btn-primary"><i class="glyphicon glyphicon-open"></i> <?php $this->show('More options'); ?></button>
    <button data-button="cancel" data-url="<?php echo $this->url('News:Admin:Browser@indexAction'); ?>" class="btn btn-default"><i class="glyphicon glyphicon-floppy-remove"></i> <?php $this->show('Cancel'); ?></button>
    
</form>

<?php else: ?>

<div class="well">
 <div class="center-block">
  <h2 class="text-muted text-center"><i class="glyphicon glyphicon-remove"></i> <?php $this->show('Before you add a post, you need to create at least one category'); ?></h2>
 </div>
</div>

<?php endif; ?>
